<?php
function compare(){
  $before = array();
  $after = array();
  $diff = array();

  foreach(glob('images/after/*.*') as $pathA){
    $pathEx = explode('/', $pathA);
    array_push($after,$pathEx[2]);
  }

  foreach(glob('images/before/*.*') as $pathB){
    $pathEx = explode('/', $pathB);
    array_push($before,$pathEx[2]);
  }

  foreach(glob('images/diff/*.*') as $pathD){
    $pathEx = explode('/', $pathD);
    array_push($diff,$pathEx[2]);
  }

  $diffBA = array_diff($before, $after);
  $diffAB = array_diff($after, $before);

  $all_cases = array(
    $diff,
    $diffAB,
    $diffBA
  );

  // Total of cases which appear only on A and B
  $noComparison = count($diffAB) + count($diffBA);

  // Total of images generated by smoke test
  $totalImages = count(array_unique(array_merge($before, $after)));

  // Total of images without difference
  $noDifference = $totalImages - count($all_cases);

  echo  '<div class="row">' .
          '<div class="report">' .
            '<div class="text-primary">Difference: <span>'. number_format((count($diff) / $totalImages) * 100, 2, '.', '') . '%</span></div>' .
            '<div class="text-primary">No difference: <span>' . number_format(($noDifference / $totalImages) * 100, 2, '.', '') . '%</span></div>' .
            '<div class="text-primary">No comparison: <span>' . number_format(($noComparison / $totalImages) * 100, 2, '.', '') . '%</span></div>' .
          '</div>' .
        '</div>';

  $all_cases_final = call_user_func_array('array_merge', $all_cases);

  sort($all_cases_final);

  return($all_cases_final);
}
?>
